FROM python:3.13.7-alpine3.21

WORKDIR /app

RUN pip install grpcio grpcio-tools "fastapi[standard]"

COPY ./task_manager.proto .

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. task_manager.proto

COPY ./cliente.py .

CMD ["uvicorn", "cliente:app", "--host", "0.0.0.0"]